name: Wineroom
analytics: {}
purpose:
  - type: contact
    url: 'mailto:winedownqrizma@gmail.com'
    label: Contact me
  - type: contact
    url: 'tel:6612353095'
    label: Call (661) 235-3095
github: true
description: DC Premium Wine Club Member
author:
  name: Ken Hutchison
  url: www.directcellars.com/wineroom
  email: winedownqrizma@gmail.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.8455153454560786
color:
  lightness: 0.8046460824552923
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  saturation: 0.7858220019843429
  brandStrength: 0.3472920393105596
  rhythmicContrast: 0.4185382758732885
content_rating:
  adult: false
typography_spectrum: 0.600618724245578
opengraph: {}
title: Winedown Qrizma
